Repository SoWellApp/hiring-test.stepper-form, pull requests merged in 2024-03, with the labels that each got.

#15 ui-733-creer-un-component-pour-afficher-les-infos-de-chaque-user
  src/components/User/ListItem.vue
  src/models/UserInterface.ts
  src/pages/UserList.vue
Labels: Small

#14 ui-730-ticket-rafenitra
  index.html
  package.json
  quasar.config.js
  src/boot/pouchorm.ts
  src/components/itemLists.vue
  src/global.d.ts
  src/pages/AuthPage.vue
  src/pages/Posts/PostPage.vue
  src/pouchorm/postCollection.ts
  src/router/routes.ts
  src/stores/posts.ts
  src/types/index.ts
  yarn.lock
Labels: Medium

#16 ui-735-creer-un-component-pour-afficher-les-infos-de-chaque-user
  src/components/ListItem.vue
  src/pages/ListPage.vue
  src/pages/data.json
  src/types/interfaces/index.d.ts
Labels: Large

#13 ui-731-ticket-ny-onja
  src/components/ListItem.vue
  src/pages/ListPage.vue
  src/pages/data.json
  src/router/routes.ts
  src/types/interfaces/index.d.ts
Labels: Large

#18 ui-734-faire-un-appel-api-via-axios-pour-recuperer-les-infos-des
  src/boot/axios.ts
  src/components/ListItem/ListItem.vue
  src/components/ListItem/LoadListItem.vue
  src/models/UserInterface.ts
  src/pages/UserList.vue
  src/services/UserService.ts
  src/stores/user-store.ts
Labels: Medium

#12 ui-732-ticket-fana
  src/boot/axios.ts
  src/components/ListItem/ListItem.vue
  src/components/ListItem/LoadListItem.vue
  src/layouts/MainLayout.vue
  src/models/UserInterface.ts
  src/pages/UserList.vue
  src/router/routes.ts
  src/services/UserService.ts
  src/stores/user-store.ts
Labels: Medium

#23 ui-742-test-playwright-ny-onja
  .vscode/settings.json
  playwright.config.ts
  quasar.config.js
  src/boot/pinia.ts
  src/components/ListItem.vue
  src/layouts/MainLayout.vue
  src/pages/ListPage.vue
  src/router/routes.ts
  src/stores/index.ts
  src/stores/user.store.ts
  tests/base-fixtures.ts
  tests/integration/navigate-through-the-app/authenticate/authenticate-with-my-email-and-password/steps/index.ts
  tests/integration/view-users-list/fixture/users.ts
  tests/integration/view-users-list/index.feature
  tests/integration/view-users-list/steps/index.ts
Labels: Large

#22 ui-741-test-playwright-fana
  .vscode/settings.json
  quasar.config.js
  src/boot/pinia.ts
  src/components/ListItem/ListItem.vue
  src/layouts/MainLayout.vue
  src/pages/AuthPage.vue
  src/pages/UserList.vue
  src/stores/index.ts
  src/stores/user-store.ts
  tests/base-fixtures.ts
  tests/integration/view-users-list/fixture/users.ts
  tests/integration/view-users-list/index.feature
  tests/integration/view-users-list/steps/index.ts
  yarn.lock
Labels: Large

#24 ui-744-playwright-2-fana
  src/pages/AuthPage.vue
  tests/integration/authenticate-with-an-username-and-password/index.feature
  tests/integration/authenticate-with-an-username-and-password/steps/index.ts
  yarn.lock
Labels: Large

#29 ui-748-creer-le-component-sw-random-number-generator
  package.json
  src/components/SwRandomNumberGenerate.vue
  src/pages/UserList.vue
  tests/integration/view-users-list/steps/index.ts
  yarn.lock
Labels: Small

#28 ui-749-creer-le-component-sw-random-number-generator-copy
  package.json
  src/components/ListItem.vue
  src/components/SwRandomNumberGenerator.vue
  src/pages/ListPage.vue
  src/stores/index.ts
  yarn.lock
Labels: Medium

#26 ui-743-test-playwright-rafenitra
  package.json
  quasar.config.js
  src/boot/pinia.ts
  src/boot/pouchorm.ts
  src/components/itemLists.vue
  src/global.d.ts
  src/layouts/MainLayout.vue
  src/pages/AuthPage.vue
  src/pages/Posts/PostPage.vue
  src/pouchorm/postCollection.ts
  src/router/routes.ts
  src/stores/index.ts
  src/stores/posts.ts
  tests/base-fixtures.ts
  tests/integration/navigate-through-the-app/authenticate/authenticate-with-my-email-and-password/fixtures.ts
  tests/integration/navigate-through-the-app/authenticate/authenticate-with-my-email-and-password/index.feature
  tests/integration/navigate-through-the-app/authenticate/authenticate-with-my-email-and-password/steps/index.ts
  tests/integration/navigate-through-the-app/authenticate/get-redirected-to-the-login-page/get-redirected-to-the-login-page/index.feature
  tests/integration/navigate-through-the-app/authenticate/get-redirected-to-the-login-page/get-redirected-to-the-login-page/steps/index.ts
  tests/integration/view-posts/fixture/posts.ts
  tests/integration/view-posts/index.feature
  tests/integration/view-posts/steps/index.ts
  tests/pages/auth-page.ts
Labels: Extra Large

#33 ui-750-sw-patrimony-search
  package.json
  src/components/SwPatrimonySearch.vue
  src/pages/ReporterPage/PatrimonyPage.vue
  src/router/routes.ts
  src/stores/user-store.ts
  src/types/index.ts
  src/utils/directives/HighLigth.ts
  yarn.lock
Labels: Medium

#31 ui-752-sw-map-displayer
  package.json
  quasar.config.js
  src/boot/google-maps.ts
  src/components/swMapDisplayer.vue
  src/pages/AuthPage.vue
  src/pages/MapDisplayer.vue
  src/router/routes.ts
  yarn.lock
Labels: Medium

#32 ui-751-sw-action-card
  src/components/sw-action-card.vue
  src/pages/ComponentPage.vue
Labels: Medium
